name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  osx_10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_osx.sh
  windows_2016:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Build
        shell: pwsh
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda create --name heyoka
          conda activate heyoka
          conda install mamba -y
          mamba install -y cmake llvmdev boost-cpp xtensor xtensor-blas blas blas-devel fmt clang ninja
          mkdir build
          cd build
          cmake ../ -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH=%CONDA_PREFIX_PATH% -DHEYOKA_BUILD_TESTS=yes -DHEYOKA_ENABLE_IPO=yes -DBoost_NO_BOOST_CMAKE=ON
          cmake --build . -- -v
